name: Build Release

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: prebuild
        run: |
          mkdir -p Assemblies
          mkdir -p ${{ runner.temp }}/downloads

      - name: build loader
        run: |
          TEMP=${{ runner.temp }}/ python Make.py --csproj Source/Loader/Loader.csproj --output Assemblies/0CombatExtendedLoader.dll --download-libs --all-libs
      - name: build core
        run: |
          TEMP=${{ runner.temp }}/ python Make.py --csproj Source/CombatExtended/CombatExtended.csproj --output Assemblies/CombatExtended.dll --download-libs --all-libs --publicizer $PWD/AssemblyPublicizer
      #- name: build compat
      #  run: |
      #    TEMP=${{ runner.temp }}/ python BuildCompat.py
      - name: package
        run: |
          mkdir RWAILib
          cp -r Assemblies/ AssembliesCore/ AssembliesCompat/ About/ Defs/ Languages/ Patches/ Royalty/ Ideology/ Biotech/ Sounds/ Textures/ ModPatches/ LoadFolders.xml README.md SupportedThirdPartyMods.md CombatExtended
          zip -9 -r CombatExtended.zip CombatExtended
      - name: Create tarball sha256
        run: |
          curl -sL "${{ github.server_url }}/${{ github.repository }}/archive/refs/tags/${{ github.ref_name }}.tar.gz" | shasum -a 256 | cut -d " " -f 1
      - name: Upload Package
        id: upload-package
        uses: actions/upload-artifact@v4
