name: Release

env:
  # Change this to point to your solution, or the folder in which your solution 
  # can be found.
  SLN_PATH: .
  # Change this to what you want your folder name to be in people's Mods/
  # folder. It should be unique to your mod.
  MOD_NAME: RWAILib
  # These two environment variables control whether all releases created by the
  # release job are drafts or prereleases.
  RELEASE_DRAFT: true
  RELEASE_PRERELEASE: false

on:
  push:
    tags:
      # This will only run the release workflow when it's tagged with a version
      # tag.
      - 'v*'

permissions: read-all


jobs:
  build:
    name: Build on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        # You can configure operating systems to build on here. It shouldn't make a difference 
        operating-system: [ubuntu-latest]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
      
    - name: Install Mod Dependencies
      run: dotnet restore ${{ env.SLN_PATH }}

    - name: Build Mod
      run: dotnet build ${{ env.SLN_PATH }} --configuration Debug --no-restore

    # I don't know how well testing will work without Rimworld actually installed. 
    # But if you have unit tests configured to work with dotnet, you may be able 
    # to uncomment this and add a testing step.
    # - name: Test Mod
    #   run: dotnet test ${{ env.SLN_PATH }} --no-restore --verbosity normal

    # There is no `zip` command on windows so you need to use tar.
    # - name: Zip-up Mod
    #   run: tar --exclude="*." -zcvf dist.tar.gz About/ Assemblies/ Defs/ Languages/ Patches/ RimCI/ Sounds/ Textures/

    # To modify this with your own directory structure, just change the paths to 
    # whatever you want. It will not upload any empty directories, those with only
    # hidden files will also be excluded.
    - name: Upload Mod Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        retention-days: 7
        path: |
          About/
          Assemblies/
          Defs/
          Languages/
          LICENSE
          Patches/
          Sounds/
          Source/
          Textures/
          !**/.*
        # This final path is to exclude hidden files such as .gitkeep and .DS_STORE. 
        # I would recommend keeping it, but I don't think it will break anything if 
        # you remove or modify it.

  package:
    name: Package
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Set Environment Variables
      # This is a special syntax for GitHub Actions that sets an environment
      # variable. See: https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
      run: echo "::set-env name=MOD_PATH::$HOME/$MOD_NAME"
    
    - name: Create Mod Folder
      run: mkdir -p ${{ env.MOD_PATH }}

    - name: Download Mod Artifacts from Build Step
      uses: actions/download-artifact@v4
      with:
        name: build
        path: ${{ env.MOD_PATH }}

    # If you have any other Rimworld folders that didn't get scooped up in the
    # artifacts, add them here. It may be neccessary to change this for v1.1 mods.
    - name: Create Mod Folders
      run: |
        mkdir -p ${{ env.MOD_PATH }}/About
        mkdir -p ${{ env.MOD_PATH }}/Assemblies
        mkdir -p ${{ env.MOD_PATH }}/Defs
        mkdir -p ${{ env.MOD_PATH }}/Languages
        mkdir -p ${{ env.MOD_PATH }}/Patches
        mkdir -p ${{ env.MOD_PATH }}/Sounds
        mkdir -p ${{ env.MOD_PATH }}/Source
        mkdir -p ${{ env.MOD_PATH }}/Textures

    - name: Zip Mod
      run: | 
        cd $HOME
        zip -r ./${{ env.MOD_NAME }}.zip ./${{ env.MOD_NAME }}/*

    - name: Upload Mod Zip Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.MOD_NAME }}
        path: ${{ env.MOD_PATH }}.zip
        retention-days: 5